# Generated by Django 2.1.5 on 2019-02-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('Suma', 'Suma'), ('Resta', 'Resta'), ('Potencia', 'Potencia')], max_length=20)),
            ],
        ),
    ]
